import { NgModule } from '@angular/core';
import { MatFormFieldModule, MatCardModule,
         MatButtonModule, MatInputModule,
         MatIconModule, MatSelectModule,
         MatToolbarModule, MatMenuModule,
         MatProgressSpinnerModule, MatListModule,
         MatSnackBarModule, MatOptionModule,
         MatDialogModule, MatTableModule,
         MatCheckboxModule, MatDatepickerModule,
         MatNativeDateModule, MatTabsModule,
         MatAutocompleteModule,
         MatSlideToggleModule,
         MatSliderModule,
         MatChipsModule,
         MatTooltipModule,
         MatSortModule } from '@angular/material';

/**
 * Module par lequel sont exportés les composants de la bibliothèque material
 * qui sont nécessaires à l'application.
 */
@NgModule({
  imports: [
    MatFormFieldModule,
    MatCardModule,
    MatButtonModule,
    MatInputModule,
    MatIconModule,
    MatToolbarModule,
    MatSelectModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatSnackBarModule,
    MatOptionModule,
    MatDialogModule,
    MatTableModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatTabsModule,
    MatSortModule,
  ],
  exports: [
    MatFormFieldModule,
    MatCardModule,
    MatButtonModule,
    MatInputModule,
    MatIconModule,
    MatToolbarModule,
    MatSelectModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatSnackBarModule,
    MatOptionModule,
    MatDialogModule,
    MatTableModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatTooltipModule,
    MatTabsModule,
    MatSortModule,
  ],
  providers: [
    // {provide: MATERIAL_COMPATIBILITY_MODE, useValue: true},
    ],
})
export class MaterialModule { }
